version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  cooldown:
    default-days: 2
  schedule:
    interval: daily
  open-pull-requests-limit: 10
